name: rondo_flutter_common
description: A new Flutter package.
version: 0.0.1
author: ikecoolon@hotmail.com
homepage: https://github.com/ikecoolon/rondo-flutter-common.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #http 分析工具
  alice: ^0.1.3
  # 封装http请求
  dio: ^3.0.10
  # 网络连接状态
  connectivity: ^0.4.2+1
  # 获取设备信息
  device_info: ^0.4.0+2
  #获取版本号
  package_info: ^0.4.0+2
  # 本地存储
  shared_preferences: ^0.5.6+3
  # 事件总线
  event_bus:  ^1.1.0
  # 提示窗口
  fluttertoast: ^3.1.3
  # webview 插件
  flutter_webview_plugin: ^0.3.10+1
  # 状态管理
  flutter_redux: ^0.5.2
  #  扫码插件
  qr_code_scanner: 0.0.13
  # 弹窗
  toast: ^0.1.3
  # 不同屏幕尺寸兼容工具
  flutter_screenutil: ^0.4.2
  # 高德地图
  amap_all_fluttify: ^0.17.0
  # 占位符
  shimmer: ^1.0.0
  # 序列化工具
  json_annotation: ^2.0.0
  # 加载动画
  flutter_spinkit: ^2.0.1
  # 状态条
  flutter_statusbarcolor: ^0.2.3
  # 加密算法库
  pointycastle: ^1.0.1
  cryptoutils: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  assets:
    - static/secret/sm3Sm2.html
